type DistanceMeasurement {
    measurementTime: String
    measurement: DistanceMeasurementData
    meta: MetaData
}

type DistanceMeasurementData {
    value: Float
}

type MetaData {
    operator: String
}

type Query {
    getTempData: DistanceMeasurement
}